steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/arboreal-vision-339901/docker-images-repo/reengage-ops-dashboard-v2:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/arboreal-vision-339901/docker-images-repo/reengage-ops-dashboard-v2:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'reengage-ops-dashboard-v2'
      - '--image=us-central1-docker.pkg.dev/arboreal-vision-339901/docker-images-repo/reengage-ops-dashboard-v2:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--memory=2048Mi'
      - '--min-instances=0'
      - '--max-instances=3'
      - '--timeout=3600'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=arboreal-vision-339901:us-central1:mysqladmin'
      - '--set-env-vars=DB_HOST=/cloudsql/arboreal-vision-339901:us-central1:mysqladmin,DB_USER=loop,DB_PASSWORD=password,DB_NAME=loop_core'

images:
  - 'us-central1-docker.pkg.dev/arboreal-vision-339901/docker-images-repo/reengage-ops-dashboard-v2:$COMMIT_SHA'
